version: '3'

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      PORT: 3000
      KEY: secretkey
      MONGO_URL: mongodb://mongo:27017/gateway
    command: npm run dev 
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    ports:
      - 27017:27017 
    volumes:
      - ./.mongo-data:/data/db
