version: '3.5'

services:
  api:
    build: .
    ports:
      - ${PORT}:3000
    volumes:
      - .:/api
      - /api/node_modules
    env_file:
      - .env
    command: npm run dev 
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    ports:
      - 27017:27017 
    volumes:
      - ./.mongo-data:/data/db
